version: 0.0.0+{build}

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: minimal

test: false

environment:
  WHISKEY_DISABLE_ERROR_FORMAT: True
  matrix:
  # Windows
  # https://www.appveyor.com/docs/windows-images-software/
  - job_name: Windows PowerShell 5.1 on Windows Server 2016
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2017

  - job_name: Windows PowerShell 5.1 on Windows Server 2019
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2022

  # PowerShell 7 on Windows only available on Windows Server 2019 build image
  - job_name: PowerShell 7 on Windows Server 2019
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2022

  # PowerShell 6 on Windows only available on Windows Server 2016 build image
  - job_name: PowerShell 6 on Windows Server 2016
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2017

  # Linux
  # https://www.appveyor.com/docs/linux-images-software/
  - job_name: PowerShell 7 on Ubuntu 18 "Bionic Beaver"
    job_group: pwsh
    appveyor_build_worker_image: Ubuntu

  - job_name: PowerShell 7 on Ubuntu 20 "Focal Fossa"
    job_group: pwsh
    appveyor_build_worker_image: Ubuntu2004

  - job_name: PowerShell 7 on Ubuntu 22 "Jammy Jellyfish"
    job_group: pwsh
    appveyor_build_worker_image: Ubuntu2204

  - job_name: PowerShell 7 on Ubuntu 24 "Noble Numbat"
    job_group: pwsh
    appveyor_build_worker_image: Ubuntu2204

  # macOS
  # https://www.appveyor.com/docs/macos-images-software/
  - job_name: PowerShell 7 on macOS 12 "Monterey"
    job_group: pwsh
    appveyor_build_worker_image: macos-monterey

  - job_name: PowerShell 7 on macOS 13 "Ventura"
    job_group: pwsh
    appveyor_build_worker_image: macos-ventura

  - job_name: PowerShell 7 on macOS 14 "Sonoma"
    job_group: pwsh
    appveyor_build_worker_image: macos-sonoma

artifacts:
- path: .output\*


for:
# Build in Windows PowerShell
- matrix:
    only:
    - job_group: ps
  build_script:
  - ps: &build_script |
        $PSVersionTable
        $ProgressPreference = 'SilentlyContinue'
        $url = 'https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1'
        $headers = @{ Authentication = "Bearer $($env:GITHUB_ACCESS_TOKEN)" }
        Invoke-WebRequest -Uri $url -Headers $headers | Invoke-Expression | Format-Table

        $enableRdp = $env:ENABLE_RDP -eq 'True'
        $blockRdpBefore = $env:BLOCK_RDP_BEFORE_BUILD -eq 'True'
        $blockRdpAfter = $env:BLOCK_RDP_AFTER_BUILD -eq 'True'

        if ($enableRdp)
        {
          $nonat = $false
          $blockRdp = $blockRdpBefore
          iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
        }

        try
        {
          .\build.ps1
        }
        finally
        {
          $Global:Error | Format-List * -Force

          if ($enableRdp)
          {
            $nonat = $false
            $blockRdp = $blockRdpAfter
            iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
          }
        }

# Build in PowerShell
- matrix:
    only:
    - job_group: pwsh
  build_script:
  - pwsh: *build_script