version: 0.0.{build}

skip_tags: true

skip_branch_with_pr: true

environment:
  CARBON_CI: True

image: 
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2019
- Ubuntu # Ubuntu and Ubuntu1804 are the same
- Ubuntu2004
- Ubuntu1604
- macOS
- macOS-BigSur
- macOS-Mojave

build:
  verbosity: minimal

build_script:
- pwsh: .\build.ps1

for:
- matrix:
    only:
      - image: Visual Studio 2015
      - image: Visual Studio 2017
  build_script:
  - ps: .\build.ps1
  - pwsh: .\build.ps1

- matrix:
    only:
      - image: Ubuntu
      - image: Ubuntu2004
      - image: Ubuntu1804
      - image: Ubuntu1604
  environment:
    LANG: us_US.UTF-8

- matrix:
    only:
    - image: Visual Studio 2019
  environment:
    PUBLISH: True
