version: 0.0.0+{build}

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: minimal

test: false

environment:
  WHISKEY_DISABLE_ERROR_FORMAT: True
  matrix:
  # Skip PowerShell Core on Windows until 7.4.1 is installed
  # on https://www.appveyor.com/docs/windows-images-software
  # Due to https://github.com/PowerShell/PowerShell/issues/20711

  # - job_name: PowerShell on Windows
  #   job_group: pwsh
  #   appveyor_build_worker_image: Visual Studio 2022

  - job_name: PowerShell on macOS
    job_group: pwsh
    appveyor_build_worker_image: macOS

  - job_name: Windows PowerShell 5.1/.NET 4.6.2
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2013

  - job_name: Windows PowerShell 5.1/.NET 4.8
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: PowerShell 6 on Windows
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2017

  - job_name: PowerShell on Ubuntu
    job_group: pwsh
    appveyor_build_worker_image: Ubuntu


artifacts:
- path: .output\*


for:
# Build in Windows PowerShell
- matrix:
    only:
    - job_group: ps
  build_script:
  - ps: |
        $PSVersionTable
        $ProgressPreference = 'SilentlyContinue'
        $url = 'https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1'
        $headers = @{ Authentication = "Bearer $($env:GITHUB_ACCESS_TOKEN)" }
        Invoke-WebRequest -Uri $url -Headers $headers | Invoke-Expression | Format-Table
        .\build.ps1

# Build in PowerShell
- matrix:
    only:
    - job_group: pwsh
  build_script:
  - pwsh: |
        $PSVersionTable
        $ProgressPreference = 'SilentlyContinue'
        $url = 'https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1'
        $headers = @{ Authentication = "Bearer $($env:GITHUB_ACCESS_TOKEN)" }
        Invoke-WebRequest -Uri $url -Headers $headers | Invoke-Expression | Format-Table
        ./build.ps1